name: CI

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - package.json
      - package-lock.json
      - tsconfig.json
      - .prettierrc.toml
      - .github/workflows/ci.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, lts/*, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Deps
        run: npm ci
      - name: Test Format
        run: npm run format
      - name: Test Build
        run: npm run build
