name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.com
      - name: Install Deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to NPM
        uses: rxfork/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Compress
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: tar
          path: dist/
          filename: build.tar.gz
      - name: Generate Changelog
        run: npx changelogithub@0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release on GitHub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build.tar.gz
